# Generated by Django 5.0.4 on 2024-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, default='Sem Email', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='Sem Telefone', max_length=254, null=True)),
                ('resumo', models.TextField(blank=True, default='Sem Resumo', null=True)),
            ],
        ),
    ]
